export const countiesToCities = {
  Carlow: [
    "Carlow Town",
    "Tullow",
    "Muine Bheag (Borrisokane)",
    "Borris",
    "Leighlinbridge",
    "Tullowbridge",
    "Ballon",
    "Castlecomer",
  ],
  Cavan: [
    "Cavan Town",
    "Ballyjamesduff",
    "Virginia",
    "Bailieborough",
    "Kingscourt",
    "Belturbet",
    "Swanlinbar",
    "Butlersbridge",
    "Drumalee",
    "Shercock",
  ],
  Clare: [
    "Ennis",
    "Shannon",
    "Kilrush",
    "Killaloe",
    "Lisdoonvarna",
    "Doonbeg",
    "Sixmilebridge",
    "Miltown Malbay",
    "Newmarket-on-Fergus",
    "Mullagh",
    "Kilmihil",
  ],
  Cork: [
    "Cork City",
    "Mallow",
    "Kinsale",
    "Midleton",
    "Clonakilty",
    "Bantry",
    "Youghal",
    "Bandon",
    "Skibbereen",
    "Cobh",
    "Fermoy",
    "Mallow",
    "Midleton",
    "Kinsale",
    "Clonakilty",
    "Bandon",
    "Skibbereen",
    "Carrigtwohill",
    "Youghal",
    "Ballincollig",
    "Ballinascorney",
    "Inchigeelagh",
    "Bantry",
    "Killeagh",
    "Drimoleague",
  ],
  Donegal: [
    "Letterkenny",
    "Donegal Town",
    "Buncrana",
    "Ballybofey",
    "Bundoran",
    "Dunfanaghy",
    "Killybegs",
    "Milford",
    "Lifford",
    "Dungloe (An Clochán Liath)",
    "Glenties",
    "Ardara",
    "Moville",
    "Raphoe",
    "Stranorlar",
    "Creeslough",
  ],
  Dublin: [
    "Dublin City",
    "Swords",
    "Drogheda",
    "Tallaght",
    "Blanchardstown",
    "Bray",
    "Malahide",
    "Greystones",
    "Maynooth",
    "Navan (partly in Meath)",
    "Lucan",
    "Celbridge",
    "Ashbourne",
    "Balbriggan",
    "Kilcock",
    "Leixlip",
    "Dalkey",
    "Howth",
    "Rathcoole",
    "Clonsilla",
    "Firhouse",
  ],
  Galway: [
    "Galway City",
    "Tuam",
    "Loughrea",
    "Ballinasloe",
    "Clifden",
    "Oranmore",
    "Athenry",
    "Gort",
    "Ballindine",
    "Carnmore",
    "Kinvara",
    "Salthill",
    "Barna",
    "Cregmore",
    "Spiddal (An Spidéal)",
    "Letterfrack",
  ],
  Kerry: [
    "Tralee",
    "Killarney",
    "Listowel",
    "Dingle (An Daingean)",
    "Killorglin",
    "Kenmare",
    "Cahersiveen",
    "Valentia",
    "Beaufort",
    "Ballybunion",
    "Ballyheigue",
    "Killorglin",
    "Kenmare",
    "Sneem",
    "Waterville",
    "Cahersiveen",
    "Glenbeigh",
  ],
  Kildare: [
    "Naas",
    "Newbridge",
    "Kildare Town",
    "Maynooth",
    "Celbridge",
    "Leixlip",
    "Monasterevin",
    "Maynooth",
    "Kilcock",
    "Prosperous",
    "Clane",
    "Ardclough",
    "Allenwood",
    "Sallins",
    "Johnstownbridge",
    "Kilteel",
  ],
  Kilkenny: [
    "Kilkenny City",
    "Thomastown",
    "Callan",
    "Castlecomer",
    "Bennettsbridge",
    "Durrow",
    "Mullinavat",
    "Freshford",
    "Tullaroan",
    "Gowran",
    "Inistioge",
  ],
  Laois: [
    "Portlaoise",
    "Mountmellick",
    "Abbeyleix",
    "Mountrath",
    "Borris-in-Ossory",
    "Stradbally",
    "Emo",
    "Rosenallis",
    "Timahoe",
    "Ballacolla",
    "The Swan",
    "Mountmellick",
  ],
  Leitrim: [
    "Carrick-on-Shannon",
    "Manorhamilton",
    "Drumshanbo",
    "Ballinamore",
    "Aughawillan",
    "Glenfarne",
    "Rossinver",
    "Dromahair",
  ],
  Limerick: [
    "Limerick City",
    "Adare",
    "Newcastle West",
    "Kilmallock",
    "Rathkeale",
    "Abbeyfeale",
    "Oola",
    "Bruff",
    "Tourin",
    "Cappamore",
    "O'Briensbridge",
    "Askeaton",
    "Fedamore",
    "Raheen",
  ],
  Longford: [
    "Longford Town",
    "Granard",
    "Edgeworthstown (Mostrim)",
    "Ballymahon",
    "Ballymahon",
    "Granard",
    "Edgeworthstown",
    "Kiltoom",
    "Abbeyshrule",
    "Drumlish",
    "Ardagh",
    "Strokestown",
    "Killoe",
  ],
  Louth: [
    "Drogheda",
    "Dundalk",
    "Ardee",
    "Carlingford",
    "Cooley",
    "Castlebellingham",
    "Enfield",
    "Baltray",
    "Termonfeckin",
    "Omeath",
    "Hillsborough",
    "Dowdallshill",
  ],
  Mayo: [
    "Castlebar",
    "Ballina",
    "Westport",
    "Claremorris",
    "Ballinrobe",
    "Belmullet",
    "Swinford",
    "Foxford",
    "Ballaghaderreen",
    "Knock",
    "Cong",
    "Louisburgh",
    "Ballycastle",
    "Clifden",
    "Newport",
  ],
  Meath: [
    "Navan",
    "Kells",
    "Trim",
    "Ashbourne",
    "Ratoath",
    "Dunshaughlin",
    "Dunboyne",
    "Ashbourne",
    "Ratoath",
    "Dunshaughlin",
    "Slane",
    "Martinstown",
    "Kilskyre",
  ],
  Monaghan: [
    "Monaghan Town",
    "Carrickmacross",
    "Castleblayney",
    "Clones",
    "Ballybay",
    "Inniskeen",
    "Scotstown",
    "Emyvale",
  ],
  Offaly: [
    "Tullamore",
    "Birr",
    "Edenderry",
    "Clara",
    "Banagher",
    "Ferbane",
    "Rhode",
    "Shinrone",
    "Durrow",
    "Portarlington",
  ],
  Roscommon: [
    "Roscommon Town",
    "Boyle",
    "Castlerea",
    "Ballaghaderreen",
    "Elphin",
    "Ballyhaunis",
    "Athleague",
    "Knockcroghery",
    "Cloonfad",
    "Crossmolina",
    "Carrick-on-Shannon (partly in Leitrim)",
  ],
  Sligo: [
    "Sligo Town",
    "Tubbercurry",
    "Ballymote",
    "Enniscrone",
    "Achonry",
    "Aclare",
    "Ballaghnatrillick",
    "Ballinafad",
    "Ballincar",
    "Ballintogher",
    "Ballygawley",
    "Ballynacarrow",
    "Ballysadare",
    "Bellaghy",
    "Beltra",
    "Bunnanadden",
    "Carney",
    "Castlebaldwin",
    "Charlestown-Bellahy",
    "Cliffoney",
    "Cloonacool",
    "Collooney",
    "Coolaney",
    "Dromore West",
    "Drumcliff",
    "Easky",
    "Geevagh",
    "Gorteen",
    "Grange",
    "Kilglass",
    "Knocknahur",
    "Monasteraden",
    "Mullaghmore",
    "Nagnata",
    "Owenbeg",
    "Rathcormack",
    "Riverstown",
    "Rosses Point",
    "Skreen",
    "Sooey",
    "Strandhill",
    "Toorlestraun",
  ],
  Tipperary: [
    "Clonmel",
    "Nenagh",
    "Thurles",
    "Cashel",
    "Tipperary Town",
    "Carrick-on-Suir",
    "Cahir",
    "Newport",
    "Borrisokane",
    "Roscrea",
    "Kilruane",
    "Golden",
    "Tipperary Town",
    "Templemore",
  ],
  Waterford: [
    "Waterford City",
    "Dungarvan",
    "Tramore",
    "Lismore",
    "Portlaw",
    "Carrick-on-Suir",
    "Kilmacthomas",
    "Cappoquin",
    "Youghal",
    "Ballymacarbry",
    "Dungarvan",
    "Tramore",
    "Passage East",
    "Ballygunner",
  ],
  Westmeath: [
    "Mullingar",
    "Athlone",
    "Kinnegad",
    "Moate",
    "Castlepollard",
    "Delvin",
    "Rochfortbridge",
    "Tyrrellspass",
    "Castlemaine",
    "Ferbane",
  ],
  Wexford: [
    "Wexford Town",
    "Gorey",
    "New Ross",
    "Enniscorthy",
    "Bunclody",
    "Rosslare Europort",
    "Arklow",
    "Ballygarrett",
    "Courtown",
    "Bridgetown",
  ],
  Wicklow: [
    "Wicklow Town",
    "Arklow",
    "Bray",
    "Greystones",
    "Blessington",
    "Avoca",
    "Ashford",
    "Tinahely",
    "Roundwood",
    "Rathdrum",
    "Baltinglass",
    "Enniskerry",
    "Hollywood",
  ],
};
